description: LangRec CLI
arguments:
  model:
    help: Model name
    required: true
    type: str
    choices:
      - DeepFM
      - SASRec
      - PNN
      - DCN
      - DCNV2
      - AutoInt
      - LightGDCN
      - BPR
      - ItemKNN
  dataset:
    help: Dataset name
    required: true
    type: str
    choices:
      - GOODREADS
      - MOVIELENS
      - STEAM
  representation:
    help: Representation of dataset
    required: false
    type: str
    choices:
      - id
      - text
      - sem_id
    default: id
  history_window:
    help: The length of the user behavior history window. For a positive value N, the first N items are taken from history. For a negative value N, the last N items are taken.
    required: false
    type: int
    default: -20
  source:
    help: The subset used
    required: false
    type: str
    choices:
      - original
      - test
      - finetune
    default: test
  rerun:
    required: false
    type: bool
    default: false
  gpu:
    help: The number of GPU to use. Enter -1 to use CPU.
    required: false
    type: int
  seed:
    help: The seed for RNG.
    required: false
    type: int
    default: 4141
  epochs:
    help: Amount of epochs
    required: false
    type: int
    default: 10
  topk:
    help: List of K values for which to compute K-based metrics like Recall, NDCG, MRR.
    required: false
    type: list
    list_style: comma
    default: [5, 10, 20]
  task:
    help: Recommendation task to perform
    required: false
    type: str
    choices:
      - ctr
      - drec
      - seq
    default: drec