description: LangRec CLI
arguments:
  model:
    help: Model name
    required: true
    type: str
    choices:
      - SENTENCEBERT
      - SENTENCET5
      - QWEN2_0_5B
      - QWEN2_1_5B
      - QWEN2_7B
      - QWEN2_5_7B
      - MISTRAL7B
      - PHI3_7B
      - RECGPT7B
      - LLAMA3_1
      - LLAMA3_1_DC
      - LLAMATULU_3_1
      - BERTBASE
      - BERTLARGE
      - BERTBASE_DC
      - P5BEAUTY_SMALL
      - P5BEAUTY_BASE
  dataset:
    help: Dataset name
    required: true
    type: str
    choices:
      - GOODREADS
      - MOVIELENS
      - STEAM
  task:
    help: Recommendation task to perform
    required: true
    type: str
    choices:
      - ctr
      - drec
      - seq
  metrics:
    help: Comma-separated list of metrics to use for evaluation.
    required: false
    type: list
    list_style: comma
    default: "NDCG@10,MRR,Recall@10,AUC,GAUC"
  history_window:
    help: The length of the user behavior history window. For a positive value N, the first N items are taken from history. For a negative value N, the last N items are taken.
    required: false
    type: int
    default: -20
  source:
    help: The subset used
    required: false
    type: str
    choices:
      - original
      - test
      - finetune
    default: test
  mode:
    help: Test, finetune or test&tune the model
    required: false
    type: str
    choices:
      - test
      - finetune
      - testtune
    default: test
  type:
    required: false
    type: str
    choices:
      - prompt
      - embed
    default: prompt
  rerun:
    required: false
    type: bool
    default: false
  embed_func:
    required: false
    type: str
    choices:
      - last
      - pool
    default: last
  latency:
    required: false
    type: bool
    default: false
  gpu:
    help: The number of GPU to use. Enter -1 to use CPU.
    required: false
    type: int
  seed:
    help: The seed for RNG.
    required: false
    type: int
    default: 4141