description: LangRec unique ID encoding test CLI
arguments:
  dataset:
    help: Dataset name
    required: true
    type: str
    choices:
      - GOODREADS
      - MOVIELENS
      - STEAM
  task:
    help: Task that the SID encoding is performed for
    required: false
    type: str
    choices:
      - CTR
      - DREC
      - SEQ
    default: SEQ
  gpu:
    help: The number of GPU to use. Enter -1 to use CPU.
    required: false
    type: int
