description: LangRec semantic ID encoding test CLI
arguments:
  dataset:
    help: Dataset name
    required: true
    type: str
    choices:
      - MOVIELENS
      - STEAM
      - GOODREADS
  model:
    help: Model name
    required: true
    type: str
    choices:
      - SENTENCEBERT
      - SENTENCET5
      - QWEN2_7B
      - QWEN2_1_5B
      - QWEN2_0_5B
      - DEEPSEEKR1QWEN_7B
      - MISTRAL7B
      - PHI3_7B
      - PHI2_3B
      - RECGPT7B
      - LLAMA1
      - LLAMA2
      - LLAMA3
      - LLAMA3_1
      - BERTBASE
      - BERTLARGE
      - P5BEAUTY_SMALL
      - P5BEAUTY_BASE
  task:
    help: Task that the SID encoding is performed for
    required: false
    type: str
    choices:
      - ctr
      - seq
      - drec
    default: seq
  rqvae_attrs:
    help: Comma-separated list of item features to be included
    required: false
    type: list
    list_style: comma
  rqvae_e_dim:
    help: Codebook embedding size
    required: false
    type: int
    default: 32
  rqvae_layer_sizes:
    help: Comma-separated list of latent space sizes for every RQ-VAE layer
    required: false
    type: list
    list_style: comma
    default: "2048,1024,512,256,128,64"
  rqvae_num_emb_list:
    help: Comma-separated list of numbers of embeddings at every VQ layer
    required: false
    type: list
    list_style: comma
    default: "256,256,256,256"
  rqvae_dropout_prob:
    help: Dropout probability
    required: false
    type: float
    default: 0.0
  rqvae_bn:
    help: Flag for using batch normalization
    required: false
    type: bool
    default: false
  rqvae_loss_type:
    help: Loss type
    required: false
    type: str
    choices:
      - MSE
      - L1
    default: MSE
  rqvae_quant_loss_weight:
    help: VQ quantization loss weight
    required: false
    type: float
    default: 1.0
  rqvae_beta:
    help: Beta for commitment loss
    required: false
    type: float
    default: 0.25
  rqvae_kmeans_init:
    help: Flag for initializing VQ via k-means
    required: false
    type: bool
    default: true
  rqvae_kmeans_iters:
    help: Max number of k-means iterations
    required: false
    type: int
    default: 100
  rqvae_sk_epsilons:
    help: Comma-separated list of Sinkhorn algorithm epsilons
    required: false
    type: list
    list_style: comma
    default: "0.0,0.0,0.0,0.003"
  rqvae_sk_iters:
    help: Max number of Sinkhorn algorithm iterations
    required: false
    type: int
    default: 50
  num_workers:
    help: The number of workers for handling data (CPU-bound)
    required: false
    type: int
    default: 4
  rqvae_batch_size:
    help: Batch size for training RQ-VAE
    required: false
    type: int
    default: 2048
  rqvae_lr:
    help: Learning rate
    required: false
    type: float
    default: 0.001
  rqvae_lr_scheduler_type:
    help: Scheduler
    required: false
    type: str
    choices:
      - LINEAR
      - CONSTANT
    default: CONSTANT
  rqvae_optimizer:
    help: Optimizer
    required: false
    type: str
    choices:
      - ADAM
      - SGD
      - ADAGRAD
      - RMSPROP
      - ADAMW
    default: ADAMW
  rqvae_weight_decay:
    help: L2 regularization coefficient
    required: false
    type: float
    default: 0.0
  rqvae_epochs:
    help: The number of epochs
    required: false
    type: int
    default: 100
  rqvae_warmup_epochs:
    help: The number of warmup epochs
    required: false
    type: int
    default: 50
  rqvae_save_limit:
    help: The maximum number of saved checkpoints
    required: false
    type: int
    default: 5
  rqvae_eval_step:
    help: The step frequency of evaluation
    required: false
    type: int
    default: 50
  gpu:
    help: The number of GPU to use. Enter -1 to use CPU.
    required: false
    type: int
  enc_model:
    help: Model used for encoding semantic IDs
    required: false
    type: str
    choices:
      - SENTENCEBERT
      - SENTENCET5
    default: SENTENCET5
