SENTENCEBERT: efederici/sentence-bert-base

SENTENCET5: sentence-transformers/sentence-t5-base

LLAMA:
  "3_1": meta-llama/Llama-3.1-8B-Instruct
  "3_1_DC": meta-llama/Llama-3.1-8B
  "TULU_3_1": allenai/Llama-3.1-Tulu-3.1-8B

RECGPT:
  7B: vinai/RecGPT-7B

QWEN:
  "2_0_5B": Qwen/Qwen2-0.5B-Instruct
  "2_7B": Qwen/Qwen2-7B-Instruct
  "2_5_7B": Qwen/Qwen2.5-7B-Instruct

MISTRAL:
  7B: mistralai/Mistral-7B-Instruct-v0.3

PHI:
  "3_7B": microsoft/Phi-3-small-8k-instruct

BERT:
  BASE: google-bert/bert-base-uncased
  BASE_DC: google-bert/bert-base-uncased
  LARGE: google-bert/bert-large-uncased