SENTENCEBERT:
  key: efederici/sentence-bert-base
  task: ctr
  finetune: false
  type: embed
  kind: small

SENTENCET5:
  key: sentence-transformers/sentence-t5-base
  task: ctr
  finetune: false
  type: embed
  kind: small

LLAMA3_1:
  - key: meta-llama/Llama-3.1-8B-Instruct
    task: ctr
    finetune: true
    type: prompt
    kind: large

LLAMA3_1_DC:
  key: meta-llama/Llama-3.1-8B
  task: ctr
  finetune: true
  type: encoding
  kind: large

QWEN2_1_5B:
  - key: Qwen/Qwen2-1.5B-Instruct
    task: ctr
    finetune: true
    type: prompt
    kind: small
  - key: Qwen/Qwen2-1.5B-Instruct
    task: seq
    finetune: true
    type: encoding
    kind: small
  - key: Qwen/Qwen2-1.5B-Instruct
    task: drec
    finetune: true
    type: encoding
    kind: small

QWEN2_5_7B:
  - key: Qwen/Qwen2.5-7B-Instruct
    task: ctr
    finetune: true
    type: prompt
    kind: large

MISTRAL7B:
  - key: mistralai/Mistral-7B-Instruct-v0.3
    task: ctr
    finetune: true
    type: prompt
    kind: large

BERTBASE:
  - key: google-bert/bert-base-uncased
    task: ctr
    finetune: true
    type: prompt
    kind: small
  - key: google-bert/bert-base-uncased
    task: seq
    finetune: true
    type: encoding
    kind: small
  - key: google-bert/bert-base-uncased
    task: drec
    finetune: true
    type: encoding
    kind: small

BERTLARGE:
  key: google-bert/bert-large-uncased
  task: ctr
  finetune: true
  type: prompt
  kind: small

BERTBASE_DC:
  key: google-bert/bert-base-uncased
  task: ctr
  finetune: true
  type: encoding
  kind: small

P5BEAUTY_SMALL:
  backbone: t5-small
  path: model_files/beauty-small.pth
  task: ctr
  finetune: false
  type: prompt
  kind: small

P5BEAUTY_BASE:
  backbone: t5-base
  path: model_files/beauty-base.pth
  task: ctr
  finetune: false
  type: prompt
  kind: small
