SENTENCEBERT: efederici/sentence-bert-bas

SENTENCET5: sentence-transformers/sentence-t5-base

LLAMA:
  1: huggyllama/llama-7b
  2: meta-llama/Llama-2-7b-hf
  3: meta-llama/Meta-Llama-3-8B
  3_1: meta-llama/Meta-Llama-3.1-8B

RECGPT:
  7B: vinai/RecGPT-7B

QWEN:
  2_0_5B: Qwen/Qwen2-0.5B-Instruct
  2_1_5B: Qwen/Qwen2-1.5B-Instruct
  2_7B: Qwen/Qwen2-7B-Instruct

MISTRAL:
  7B: mistralai/Mistral-7B-Instruct-v0.3

PHI:
  2_3B: microsoft/phi-2
  3_7B: microsoft/Phi-3-small-8k-instruct

BERT:
  BASE: bert-base-uncased
  LARGE: bert-large-uncased

P5:
  BEAUTY_SMALL:
    backbone: t5-small
    path: model_files/beauty-small.pth
  BEAUTY_BASE:
    backbone: t5-base
    path: model_files/beauty-base.pth